name: Generate & Deploy Mend Release Notes

# Grant write permission for GitHub Pages deployment
permissions:
  contents: write

on:
  schedule:
    # Run every Monday at 08:30 AM US Central (13:30 UTC)
    - cron: '30 13 * * 1'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Ensure job has proper permissions (inherits from workflow above)
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run RSS/HTML generator
        run: |
          python RSSFEED.py

      - name: Prepare Docs folder
        run: |
          mkdir -p docs
          mv mend_combined_release_feed.html docs/index.html
          mv mend_combined_release_feed.xml docs/rss.xml
          mv mend_combined_release_feed.atom docs/atom.xml

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
